import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
export default function Home() {
  let router = useRouter();
  const prevPage = ()=>{
    // router.push(-1)
    router.back()
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className='btn btn-outline-success' onClick={prevPage}>Prev page</button>
      </main>

    </div>
  )
}
